server:
  port: 8088  tomcat:    uri-encoding: UTF-8
#server.tomcat.uri-encoding=UTF-8

mybatis:
  mapperLocations: classpath:/mappers/*.xml
  typeAliasesPackage: com.gdufe.entity
  mapperScanPackage: com.gdufe.dao
  configLocation: classpath:/mybatis-config.xml

spring:
#解决中文乱码问题
  http:    encoding:
      force: true      charset: UTF-8      
      enabled: true
  mvc:
    pathmatch:
      use-suffix-pattern: true
#处理responseBody 里面日期类型      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    
  freemarker:
    content-type: text/html
    suffix: .ftl
    template-loader-path:    - classpath:/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##########'   #数字格式化，无小数点
      datetime_format: 'yyyy-MM-dd HH:mm:ss' #时间格式化
      default_encoding: UTF-8
      template_update_delay: 0
      #用于解决前端报空指针问题  空值判断必须${aa!}
      classic_compatible: true
  ##数据库连接信息
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/db_blog?useUnicode=true&amp;characterEncoding=utf-8
    #解决中文乱码问题
    url: jdbc:mysql://127.0.0.1:3306/db_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
